import Link from "next/link";
import { notFound } from "next/navigation";
import { sendInvitationAction, setAgencyAuthorityAction, updateProjectAction } from "@/app/studio/actions";
import { ProjectEditor } from "@/components/projects/project-editor";
import { WorkspaceShell } from "@/components/workspace/workspace-shell";
import { requireWorkspace } from "@/lib/auth/context";
import { createServerSupabaseClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
function strings(value:unknown):string[]{return Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"):[];}
export default async function ProjectDetailPage({params,searchParams}:{params:Promise<{publicId:string}>;searchParams:Promise<{notice?:string;error?:string}>}){const{publicId}=await params;if(!/^prj[0-9a-f]{24}$/.test(publicId))notFound();const viewer=await requireWorkspace("creator","studio-project-edit");const query=await searchParams;const supabase=await createServerSupabaseClient();const{data,error}=await supabase.rpc("get_project_private",{requested_public_id:publicId});if(error||!data||typeof data!=="object"||Array.isArray(data))notFound();const project=data as Record<string,unknown>,revision=typeof project.revision==="number"?project.revision:Number(project.revision??1),locked=project.state==="contract_locked";
return <WorkspaceShell email={viewer.user.email??"Verified account"} context={viewer.context}><main className="studio-page studio-page--narrow"><header className="studio-header"><div><span className="eyebrow">Versioned draft</span><h1>{String(project.title??"Project")}</h1><p>Revision {revision} · {String(project.state??"draft")}</p></div><div className="studio-actions"><Link className="studio-button" href={`/studio/projects/${publicId}/terms`}>Terms & consent</Link><Link className="studio-button" href="/studio/projects">All projects</Link></div></header>{query.error?<p className="studio-error" role="alert">{query.error==="conflict"?"This draft changed elsewhere. Reloaded state must be reviewed before saving again.":"The requested project action could not be completed safely."}</p>:null}{query.notice==="saved"?<p className="studio-notice" role="status">Revision saved.</p>:null}{!locked?<ProjectEditor action={updateProjectAction} projectPublicId={publicId} revision={revision} submitLabel="Save revision" defaults={{title:String(project.title??""),publicSynopsis:String(project.publicSynopsis??""),privateBrief:String(project.privateBrief??""),category:String(project.category??""),format:String(project.format??""),boundaries:strings(project.boundaries),compensationModel:String(project.compensationModel??"fixed"),distributionScope:String(project.distributionScope??""),rightsDeclarations:strings(project.rightsDeclarations)}}/>:<section className="studio-card"><h2>Contract locked</h2><p>This project draft can no longer be silently rewritten. Continue through the campaign preparation flow.</p><Link className="studio-button studio-button--primary" href={`/studio/projects/${publicId}/campaign`}>Campaign publishing</Link></section>}
{!locked?<section className="studio-grid studio-grid--two"><div className="studio-card"><h2>Invite collaborator</h2><p>Invitation acceptance only enters collaboration/contract preparation. It is not legal consent.</p><form action={sendInvitationAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><label>Recipient handle<input name="recipient_handle" required/></label><label>Role<input name="role_name" defaultValue="performer" required/></label><label>Proposal note<textarea name="note" rows={3} maxLength={2000}/></label><button className="studio-button studio-button--primary" type="submit">Send invitation</button></form></div><div className="studio-card"><h2>Agency communication authority</h2><p>An approved agency can communicate only after this explicit grant. It can never consent for a performer.</p><form action={setAgencyAuthorityAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><input type="hidden" name="enabled" value="true"/><label>Agency handle<input name="agency_handle" required/></label><button className="studio-button" type="submit">Grant communication authority</button></form></div></section>:null}</main></WorkspaceShell>}
