import Link from "next/link";
import { randomUUID } from "node:crypto";
import { notFound } from "next/navigation";
import { NavigationActionForm } from "@/components/forms/navigation-action-form";
import { DeliveryReviewPanel } from "@/components/production/delivery-review-panel";
import { ProductionAssetUploader } from "@/components/production/production-asset-uploader";
import { WorkspaceShell } from "@/components/workspace/workspace-shell";
import { requireAdultViewer } from "@/lib/auth/context";
import { parseProductionWorkspace } from "@/lib/production/policy";
import { parseDeliveryReviewContext } from "@/lib/review/policy";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { createProductionMilestoneAction, createProductionTaskAction, createProductionUpdateAction, issueProductionAssetAccessAction, publishReleaseAction, recordProductionApprovalAction, revokeProductionCollaboratorAction, setProductionStatusAction, setProductionTaskStatusAction, setProductionUpdateStateAction } from "./actions";

export const dynamic = "force-dynamic";
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value)) : "Not set";

export default async function ProductionWorkspacePage({ params, searchParams }: { params: Promise<{ publicId: string }>; searchParams: Promise<{ notice?: string; error?: string }> }) {
  const { publicId } = await params; if (!/^prj[0-9a-f]{24}$/.test(publicId)) notFound();
  const viewer = await requireAdultViewer(`/studio/projects/${publicId}/production`), query = await searchParams, supabase = await createServerSupabaseClient();
  const [{ data, error }, { data: reviewData, error: reviewError }] = await Promise.all([
    supabase.rpc("get_production_workspace", { requested_project_public_id: publicId }),
    supabase.rpc("get_delivery_review_context", { requested_project_public_id: publicId }),
  ]);
  const workspace = parseProductionWorkspace(data), review = parseDeliveryReviewContext(reviewData);
  if (error || reviewError || !workspace || !review) notFound();
  const deliveryIdempotencyKey = `final-${randomUUID()}`;
  const releaseIdempotencyKey = `release-${randomUUID()}`;
  const releaseMediaAssets = workspace.assets.filter((asset) => asset.kind === "media");
  return <WorkspaceShell email={viewer.user.email ?? "Verified account"} context={viewer.context}><main className="studio-page">
    <header className="studio-header"><div><span className="eyebrow">Private production workspace</span><h1>{workspace.title}</h1><p>{workspace.status.replaceAll("_", " ")} · revised estimate {date(workspace.revisedEstimate)}</p></div><div className="studio-actions"><Link className="studio-button" href={`/studio/projects/${publicId}`}>Project</Link><Link className="studio-button" href="/studio/projects">All projects</Link></div></header>
    {query.notice ? <p className="studio-notice" role="status">Production workspace updated.</p> : null}{query.error ? <p className="studio-error" role="alert">The requested production action could not be completed safely.</p> : null}
    <div className="studio-grid studio-grid--two">
      <section className="studio-card"><h2>Timeline and milestones</h2>{workspace.milestones.length ? <div className="studio-stack">{workspace.milestones.map((item)=><article key={item.publicId}><strong>{item.title}</strong><div className="studio-meta"><span>{item.status.replaceAll("_", " ")}</span><span>{date(item.dueAt)}</span></div><NavigationActionForm action={recordProductionApprovalAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><input type="hidden" name="target_public_id" value={item.publicId}/><label>Your approval<select name="state"><option value="approved">Approve</option><option value="rejected">Reject</option></select></label><label>Note<textarea name="note" maxLength={1000}/></label><button className="studio-button" type="submit">Record approval</button></NavigationActionForm></article>)}</div>:<p>No milestones yet.</p>}
      {workspace.isOwner ? <NavigationActionForm action={createProductionMilestoneAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><label>Milestone title<input name="title" maxLength={160} required/></label><label>Due date<input name="due_at" type="date"/></label><button className="studio-button studio-button--primary" type="submit">Add milestone</button></NavigationActionForm>:null}</section>
      <section className="studio-card"><h2>Team tasks</h2>{workspace.tasks.length ? <div className="studio-stack">{workspace.tasks.map((task)=><article key={task.publicId}><strong>{task.title}</strong><div className="studio-meta"><span>{task.roleName}</span><span>{task.status.replaceAll("_", " ")}</span>{task.assignedToMe?<span>Assigned to you</span>:null}</div>{workspace.isOwner||task.assignedToMe?<NavigationActionForm action={setProductionTaskStatusAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><input type="hidden" name="task_public_id" value={task.publicId}/><select name="status" defaultValue={task.status}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="done">Done</option></select><button className="studio-button" type="submit">Update task</button></NavigationActionForm>:null}<NavigationActionForm action={recordProductionApprovalAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><input type="hidden" name="target_public_id" value={task.publicId}/><select name="state"><option value="approved">Approve</option><option value="rejected">Reject</option></select><input name="note" placeholder="Optional approval note" maxLength={1000}/><button className="studio-button" type="submit">Record approval</button></NavigationActionForm></article>)}</div>:<p>No tasks yet.</p>}
      {workspace.isOwner?<NavigationActionForm action={createProductionTaskAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><label>Task<input name="title" required maxLength={200}/></label><label>Assignee handle<input name="assignee_handle" placeholder="optional"/></label><label>Project role<input name="role_name" defaultValue="collaborator" required/></label><label>Milestone<select name="milestone_public_id"><option value="">No milestone</option>{workspace.milestones.map((m)=><option key={m.publicId} value={m.publicId}>{m.title}</option>)}</select></label><button className="studio-button studio-button--primary" type="submit">Add task</button></NavigationActionForm>:null}</section>
    </div>
    <div className="studio-grid studio-grid--two">
      <section className="studio-card"><h2>Private assets</h2><p>Assets stay in the private production bucket. Each download requires a short-lived, member-bound access token.</p>{workspace.assets.map((asset)=><article key={asset.publicId}><div className="studio-meta"><span>{asset.kind}</span><span>SHA-256 {asset.sha256.slice(0,12)}…</span></div><NavigationActionForm action={issueProductionAssetAccessAction}><input type="hidden" name="project_public_id" value={publicId}/><input type="hidden" name="asset_public_id" value={asset.publicId}/><button className="studio-button" type="submit">Download securely</button></NavigationActionForm></article>)}{workspace.isOwner?<ProductionAssetUploader projectPublicId={publicId}/>:null}</section>
      <section className="studio-card"><h2>Supporter updates</h2><p>Supporters receive only updates that pass draft → approved → published.</p>{workspace.updates.map((update)=><article key={update.publicId}><strong>{update.kind.replaceAll("_", " ")} · {update.state}</strong><p>{update.body}</p>{workspace.isOwner&&update.state!=="published"?<NavigationActionForm action={setProductionUpdateStateAction}><input type="hidden" name="project_public_id" value={publicId}/><input type="hidden" name="update_public_id" value={update.publicId}/><input type="hidden" name="state" value={update.state==="draft"?"approved":"published"}/><button className="studio-button" type="submit">{update.state==="draft"?"Approve update":"Publish to supporters"}</button></NavigationActionForm>:null}</article>)}{workspace.isOwner?<NavigationActionForm action={createProductionUpdateAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><label>Update type<select name="kind"><option value="progress">Progress</option><option value="delay">Delay</option><option value="risk">Risk</option></select></label><label>Message<textarea name="body" required maxLength={4000}/></label><label>Revised estimate<input type="date" name="revised_estimate"/></label><button className="studio-button studio-button--primary" type="submit">Save draft update</button></NavigationActionForm>:null}</section>
    </div>
    <DeliveryReviewPanel projectPublicId={publicId} review={review} assets={workspace.assets} isOwner={workspace.isOwner} idempotencyKey={deliveryIdempotencyKey}/>
    {workspace.isOwner && review.current?.releaseReady ? <section className="studio-card"><span className="eyebrow">Approved final delivery</span><h2>Publish secure release</h2><p>Publication binds this listing to immutable delivery v{review.current.version}, SHA-256 {review.current.sha256.slice(0,12)}…. Repeat submissions are idempotent only when the metadata is identical.</p><NavigationActionForm action={publishReleaseAction} className="studio-form"><input type="hidden" name="project_public_id" value={publicId}/><input type="hidden" name="delivery_public_id" value={review.current.publicId}/><input type="hidden" name="idempotency_key" value={releaseIdempotencyKey}/><label>Release title<input name="title" defaultValue={workspace.title} minLength={2} maxLength={180} required/></label><label>Synopsis<textarea name="synopsis" defaultValue={`Approved final delivery version ${review.current.version}.`} minLength={3} maxLength={2000} required/></label><label>Poster asset<select name="poster_asset_public_id"><option value="">No poster</option>{releaseMediaAssets.map((asset)=><option key={asset.publicId} value={asset.publicId}>{asset.publicId} · {asset.sha256.slice(0,12)}…</option>)}</select></label><label>Preview asset<select name="preview_asset_public_id"><option value="">No preview</option>{releaseMediaAssets.map((asset)=><option key={asset.publicId} value={asset.publicId}>{asset.publicId} · {asset.sha256.slice(0,12)}…</option>)}</select></label><button className="studio-button studio-button--primary" type="submit">Publish approved release</button></NavigationActionForm></section>:null}
    {workspace.isOwner?<div className="studio-grid studio-grid--two"><section className="studio-card"><h2>Production status</h2><NavigationActionForm action={setProductionStatusAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><label>Status<select name="status" defaultValue={workspace.status}><option value="planned">Planned</option><option value="active">Active</option><option value="delayed">Delayed</option><option value="at_risk">At risk</option><option value="complete">Complete</option></select></label><label>Revised estimate<input name="revised_estimate" type="date"/></label><label>Reason<textarea name="reason" maxLength={1000}/></label><button className="studio-button studio-button--primary" type="submit">Update status</button></NavigationActionForm></section><section className="studio-card"><h2>Remove collaborator access</h2><p>Revocation is checked again on every workspace, asset-token, and storage request.</p><NavigationActionForm action={revokeProductionCollaboratorAction} className="studio-form studio-form--compact"><input type="hidden" name="project_public_id" value={publicId}/><label>Collaborator handle<input name="collaborator_handle" required/></label><label>Reason<textarea name="reason" required minLength={3} maxLength={500}/></label><button className="studio-button" type="submit">Revoke project access</button></NavigationActionForm></section></div>:null}
  </main></WorkspaceShell>;
}
