export const FOUNDATION_SLICE = {
  id: "slice-17",
  number: 17,
  name: "Administration and Launch Hardening",
  healthStatus: "ok",
  requiredRoutes: [
    "/",
    "/design-system",
    "/health",
    "/auth/login",
    "/auth/sign-up",
    "/auth/forgot-password",
    "/auth/check-email",
    "/age-assurance",
    "/access-denied",
    "/workspace",
    "/workspace/fan",
    "/workspace/creator",
    "/workspace/agency",
    "/workspace/staff",
    "/workspace/staff/role-requests",
    "/workspace/staff/verification",
    "/workspace/creator/demand",
    "/settings/security",
    "/settings/profile",
    "/settings/privacy",
    "/settings/privacy/export",
    "/settings/verification",
    "/notifications",
    "/app/feed",
    "/app/explore",
    "/app/search",
    "/app/demand",
    "/app/demand/new",
    "/app/funding",
    "/app/earnings",
    "/app/copyright",
    "/app/support",
    "/studio/projects",
    "/studio/projects/new",
    "/studio/invitations",
    "/workspace/staff/delivery-review",
    "/workspace/staff/finance",
    "/workspace/staff/copyright",
    "/workspace/staff/agency-verification",
    "/workspace/staff/operations",
    "/privacy",
    "/terms",
    "/help",
  ] as const,
} as const;

export function isFoundationRoute(pathname: string): boolean {
  return FOUNDATION_SLICE.requiredRoutes.includes(
    pathname as (typeof FOUNDATION_SLICE.requiredRoutes)[number],
  );
}
